// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9uaG6CwaNRF4iUrlNwtk8mpVfUrOE8As',
    appId: '1:978327706168:web:7239f7266b6a2ff100a4cd',
    messagingSenderId: '978327706168',
    projectId: 'aurora-smart-living',
    authDomain: 'aurora-smart-living.firebaseapp.com',
    databaseURL: 'https://aurora-smart-living-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-smart-living.firebasestorage.app',
    measurementId: 'G-W4G343N1J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLHPLlYA91W91e3k00TfetyP1LSx8A0n4',
    appId: '1:978327706168:android:caf805deec948aaa00a4cd',
    messagingSenderId: '978327706168',
    projectId: 'aurora-smart-living',
    databaseURL: 'https://aurora-smart-living-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-smart-living.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtKnHvngSAYKapj65EpzyQqpyuODyLx28',
    appId: '1:978327706168:ios:ae1e3994b7c4e00200a4cd',
    messagingSenderId: '978327706168',
    projectId: 'aurora-smart-living',
    databaseURL: 'https://aurora-smart-living-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-smart-living.firebasestorage.app',
    iosBundleId: 'com.example.smartroommonitorandcontrollersystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtKnHvngSAYKapj65EpzyQqpyuODyLx28',
    appId: '1:978327706168:ios:ae1e3994b7c4e00200a4cd',
    messagingSenderId: '978327706168',
    projectId: 'aurora-smart-living',
    databaseURL: 'https://aurora-smart-living-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-smart-living.firebasestorage.app',
    iosBundleId: 'com.example.smartroommonitorandcontrollersystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9uaG6CwaNRF4iUrlNwtk8mpVfUrOE8As',
    appId: '1:978327706168:web:8aa6c6290acfb9df00a4cd',
    messagingSenderId: '978327706168',
    projectId: 'aurora-smart-living',
    authDomain: 'aurora-smart-living.firebaseapp.com',
    databaseURL: 'https://aurora-smart-living-default-rtdb.firebaseio.com',
    storageBucket: 'aurora-smart-living.firebasestorage.app',
    measurementId: 'G-KCBDJ2XJKK',
  );
}
